# Generated by Django 3.2.14 on 2022-07-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20220712_1146'),
        ('question', '0002_alter_questionoption_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
