# Generated by Django 3.2.14 on 2022-07-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_questionoption_questions'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Imtixonlar'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjects',
        ),
        migrations.AddField(
            model_name='userexam',
            name='questions',
            field=models.ManyToManyField(editable=False, to='question.Question'),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='user_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exam.userexam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='question.Question'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='option_ids',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
