# Generated by Django 3.2.14 on 2022-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_delete_subject'),
        ('exam', '0002_auto_20220712_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Imtixon', 'verbose_name_plural': 'Imtixonlar'},
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='questions',
            field=models.ManyToManyField(to='question.Question'),
        ),
    ]
