# Generated by Django 3.2.14 on 2022-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20220712_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
